spring:
  application:
    name: file-service

  config:
    import:
      - "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL1:localhost}:9001/eureka/,http://${EUREKA_SERVER_URL2:localhost}:9002/eureka/

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace